### ISSUE TITLE
New Theme Request

### ISSUE THREAD

**Issue by JustABeginning** [vishnuvardhan-s/leetcode-custom-themes#1]
Please add **Atom One Light** & **OneDark** Themes.

**Comment by vishnuvardhan-s** [comment]
Hi @JustABeginning,

Thanks for using the extension.  I have added the themes that you requested to the extension and submitted for the store review. For the light theme, I couldn't find exact match for the CodeMirror, so I have added the nearest possible I could.  If you find something better, please create a PR.  

Dark looks like this:

![image](https://user-images.githubusercontent.com/45058522/191050378-5ca97deb-3ecd-4210-9602-4eed09f791c7.png)

Light looks like this:

![image](https://user-images.githubusercontent.com/45058522/191050498-521f7d5b-dc12-47d2-a578-4fcdae545bdd.png)

**Comment by JustABeginning** [comment]
Thank you very much ! This extension is really great 👍
