### ISSUE TITLE
[Bug] The Theme is not stable. 

### ISSUE THREAD

**Issue by dhrumilpatel30** [vishnuvardhan-s/leetcode-custom-themes#5]
The theme breaks on New UI after clicking the run button.

**Comment by vishnuvardhan-s** [comment]
I was on vacation till now. Thanks for reporting. I will check it out. 
When I took a quick look, it looks like monaco instance is recreated while clicking on run button which changes the theme back to default. I need to somehow listen to the theme change and prevent it from happening.

**Comment by dhrumilpatel30** [comment]
Hey @vishnuvardhan-s, you can also tell me for any development work. I would love to contribute in this plugin.

**Comment by vishnuvardhan-s** [comment]
@dhrumilpatel30, I believe this issue is not there now. Can you please verify it once and close this issue?

**Comment by dhrumilpatel30** [comment]
> @dhrumilpatel30, I believe this issue is not there now. Can you please verify it once and close this issue?

yes sure you can close the issue. it was just random issue and working fine now.
